version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod 
      --setParameter internalQueryCacheMaxEntriesPerCollection=5000
      --setParameter collectionSamplingLogIntervalSeconds=300
      --setParameter storageEngineConcurrentReadTransactions=128
      --setParameter storageEngineConcurrentWriteTransactions=128
      --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=3000
    container_name: cpen321_app
    volumes:
      - .:/workspace
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/biteswipe
      - NODE_ENV=production
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
    driver: local
