version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: '0.5'
        reservations:
          memory: 256M
    command: ["mongod", "--wiredTigerCacheSizeGB", "0.25"]

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: cpen321_app
    restart: unless-stopped
    environment:
      - PORT=${PORT}
      - DB_URI=${DB_URI}
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: '0.3'
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      sh -c "node --max-old-space-size=150
      --optimize-for-size
      --gc-interval=100
      dist/index.js"

volumes:
  mongo_data:
    driver: local
