version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    deploy:
      resources:
        limits:
          memory: 384M
          cpus: '0.5'
        reservations:
          memory: 256M
    command: >
      mongod 
      --wiredTigerCacheSizeGB 0.25
      --tlsMode disabled
      --setParameter internalQueryCacheMaxEntriesPerCollection=5000
      --setParameter collectionSamplingLogIntervalSeconds=300
      --setParameter storageEngineConcurrentReadTransactions=128
      --setParameter storageEngineConcurrentWriteTransactions=128
      --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=3000
    container_name: cpen321_app
    restart: unless-stopped
    environment:
      - PORT=3000
      - DB_URI=mongodb://mongo:27017/biteswipe
      - NODE_ENV=production
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    deploy:
      resources:
        limits:
          memory: 192M
          cpus: '0.3'
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        mode: "non-blocking"

volumes:
  mongo_data:
    driver: local
