version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo_instance
    restart: unless-stopped
    expose:
      - "27017"
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod 
      --setParameter internalQueryCacheMaxEntriesPerCollection=5000
      --setParameter collectionSamplingLogIntervalSeconds=300
      --setParameter storageEngineConcurrentReadTransactions=128
      --setParameter storageEngineConcurrentWriteTransactions=128
      --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

  test:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: test
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${PORT}"
    ports:
      - "9229:9229" # Debug port
    command: ["./src/scripts/runTests.sh"]
    depends_on:
      - mongo
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app_network

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
