version: "3.3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    expose:
      - "27017"
    # ports:
    #   - "27017:27017"
    volumes:
      - mongo_data:/data/db
    command: >
      mongod 
      --setParameter internalQueryCacheMaxEntriesPerCollection=5000
      --setParameter collectionSamplingLogIntervalSeconds=300
      --setParameter storageEngineConcurrentReadTransactions=128
      --setParameter storageEngineConcurrentWriteTransactions=128
      --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      app_network:
        aliases:
          - mongo

  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "${PORT}"
    ports:
      - "9229:9229" # Debug port
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      app_network:
        aliases:
          - app
    logging:
      driver: "json-file"
      
  test:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - PORT=${PORT}
    container_name: test
    env_file:
      - .env
    environment:
      - DOCKER_ENV=true
    command: ["npm", "run", "test:coverage:unmocked"]
    depends_on:
      - mongo
    volumes:
      - ./coverage:/app/backend/coverage
    networks:
      app_network:
        aliases:
          - test
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:latest
    container_name: nginx_https
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/nginx-entrypoint/nginx-entrypoint.sh:/nginx-entrypoint-inside-container.sh
      - ./nginx/certs:/etc/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
    entrypoint: ["/nginx-entrypoint-inside-container.sh"]
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - PORT=${PORT}
      - APP_HOST=app
    networks:
      app_network:
        aliases:
          - nginx
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data:
    driver: local

networks:
  app_network:
    driver: bridge
