name: "Deploy Infrastructure"

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    environment: production
    timeout-minutes: 15  # Set a timeout for the entire job

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Get PR Number
        id: pr_number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Setup Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.5.0"

      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh/to_azure
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/to_azure/CPEN321.pem
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/to_azure/CPEN321.pub
          chmod 600 ~/.ssh/to_azure/CPEN321.pem
          chmod 644 ~/.ssh/to_azure/CPEN321.pub
          ls -la ~/.ssh/

      - name: Create .env File
        working-directory: ${{ github.workspace }}
        run: |
          echo "PORT=3000" > backend/.env
          echo "DB_URI=mongodb://mongo:27017/biteswipe" >> backend/.env
          echo "NODE_ENV=test" >> backend/.env
          echo "GOOGLE_MAPS_API_KEY=${{ secrets.GOOGLE_MAPS_API_KEY }}" >> backend/.env
          echo "FIREBASE_CREDENTIALS_JSON_PATHNAME=/app/backend/biteswipe-132f1-firebase-adminsdk-fbsvc-76c5bb6fe5.json" >> backend/.env

      - name: Deploy New Infrastructure
        timeout-minutes: 5  # Set a 5-minute timeout for tests
        run: |
          cd backend/scripts
          chmod +x import_resource_group.sh
          python3 deploy_infra.py --prefix pr${{ env.PR_NUMBER}} --run-mode test
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          
      - name: Download Test Results
        run: |
          # Get VM IP from Terraform output
          cd backend/terraform
          VM_IP=$(terraform output -raw vm_public_ip)
          echo "VM IP: $VM_IP"
          
          # Create directory for test results
          mkdir -p test-results
          
          # Download coverage reports from VM
          echo "Downloading test results from VM..."
          scp -o StrictHostKeyChecking=no -i ~/.ssh/to_azure/CPEN321.pem -r adminuser@${VM_IP}:/app/backend/coverage/* test-results/
          
          # Check if download was successful
          if [ $? -eq 0 ]; then
            echo "Test results downloaded successfully"
            ls -la test-results/
          else
            echo "Failed to download test results"
            exit 1
          fi
        continue-on-error: true
        
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage-report
          path: test-results
          retention-days: 14
        continue-on-error: true
        
      - name: Destroy Infrastructure
        if: always()
        run: |
          cd backend/scripts
          python3 deploy_infra.py --prefix pr${{ env.PR_NUMBER}} --destroy
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}